# Generated by Django 6.0 on 2026-01-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='image',
        ),
    ]
