# Generated by Django 6.0 on 2025-12-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'User Stats', 'verbose_name_plural': 'User Stats'},
        ),
    ]
